### ISSUE TITLE
Compact Layout Assignments Updating Erroneously

### ISSUE THREAD

**Issue by ToAFinish** [financialforcedev/apex-mdapi#188] opened 2017-10-23 22:41 UTC
We've run into an issue which we can't seem to figure out.  We've got some code that updates a picklist, adds values and re-orders the list alphabetically.  That works well.  Then, we have a block of code, posted below, which goes through the record types and updates them as well.  However, what we are seeing is that while the code works, it is also updating the assignment of Compact Layouts on the object, which poses a problem.  We've gone through the code and can't figure out how to stop this "feature".

```java
// Updating list of record types
List < MetadataService.RecordType > TEMPRecordTypelist = new List < MetadataService.RecordType > ();
integer maxSize = 10;
for(MetadataService.RecordType TEMPrectype : recordTypeList){
    TEMPRecordTypelist.add( TEMPrectype );
    System.debug('TEMPRecordTypelist:::::::::'+TEMPRecordTypelist);
    List<MetadataService.SaveResult> results = service.updateMetadata( TEMPRecordTypelist );  
    for(MetadataService.SaveResult result : results){
        MetadataServiceExamples.handleSaveResults(result);
    }
    TEMPRecordTypelist.clear();
}
```

The content of the debug statement is attached.  Also, the reason we found this was when we were auditing the setup log, as you can see in the attached screenshot.
<img width="887" alt="audittrail" src="https://user-images.githubusercontent.com/6853052/31916661-660dd876-b819-11e7-8ca2-1549d9a59413.png">

Any idea why this is or how to stop it?

Thank you!

Joseph
[debugstatement.txt](https://github.com/financialforcedev/apex-mdapi/files/1408967/debugstatement.txt)

**Comment by ToAFinish** [comment] 2017-11-21 23:02
Hi @afawcett - this is really a bug that is affecting one of our clients.  I realize this is free of charge so you don't have to support it, but is there anything I can do to have you look at it?  Thank you!

**Comment by dfruddffdc** [comment] 2017-11-22 11:24
Hi, hope you don't mind me editing your original comment! I just formatted the code as a java code block.

You're reading RecordTypes, manipulating `picklistValues` and then saving. So far so good. But as you are probably well aware, the [RecordType](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_recordtype.htm)  has other properties, such as `fullname`, `active`, `description` and the eponymous `compactLayoutAssignment`.

In your debug log, your RecordType looks something like this

```java
RecordType:[
    active=true,
    fullName=Contact.up__Machine,
    compactLayoutAssignment=null,
    // ... some more properties, including the good ol' picklist values
]
```

And `compactLayoutAssignment=null` is where the trouble lies. I'm not sure why it's coming back as null on reading the metadata, but saving it as null reverts to 'Inherit from Primary.'
Maybe it's a bug the Metadata API which you would need to raise with Salesforce.
Or maybe the current user doesn't have permission to view that compact layout.

As a workaround, you could explicitly set the compactLayoutAssignment value - but obviously this only helps if you know the correct value for all record types.

I'm going to close this, as I think the problem is part of Salesforce's Metadata API rather than this Apex helper library.

**Closed by dfruddffdc** 2017-11-22 11:24 UTC

**Comment by afawcett** [comment] 2017-11-26 00:32
**Tip:** Run your code from Annonymous Apex and check the debug log after. It seems that in this context you get to see the raw XML requests and responses being sent and received from the Salesforce server. This may yield more insight, it also gives you something you can build into a curl script you can send to Salesforce support (without distracting them needlessly with discussions on Apex wrapping SOAP etc etc).
