### ISSUE TITLE
Add listViewButton into search layout doesn't show

### ISSUE THREAD

**Issue by Lanceshi2** [financialforcedev/apex-mdapi#144] opened 2016-09-15 23:18 UTC
I am using the below code to add a list view button into search layout: 

```
public static void addListButton()
{
    MetadataService.MetadataPort service = Util.createService();

    MetadataService.CustomObject contact_object =
        (MetadataService.CustomObject) service.readMetadata('CustomObject',  new String[] { 'Contact' }).getRecords()[0];

    if(contact_object.searchLayouts.listViewButtons == null) {
        contact_object.searchLayouts.listViewButtons = new List<String>();
    }

    contact_object.searchLayouts.listViewButtons.add('Add_To_List');

    handleSaveResults(
        service.updateMetadata(
            new MetadataService.Metadata[] {contact_object})[0]);
}
```

This code runs fine. And when I fetch the metadata from Salesforce, it also looks correct: 

```
<searchLayouts>
    <customTabListAdditionalFields>FULL_NAME</customTabListAdditionalFields>
    <customTabListAdditionalFields>ACCOUNT.NAME</customTabListAdditionalFields>
    <customTabListAdditionalFields>CONTACT.PHONE1</customTabListAdditionalFields>
    <listViewButtons>Add_To_List</listViewButtons>
```

However, the list view button is not added into the list view page. I am sure why. 

But, if I retrieve the contact.object metadata file and re-deploy the same file back into salesforce, it just works fine. I believe the tool is also using metadata api. So I would say it shouldn't be a metadata api issue. 

Is it a bug or something I have missed here?

**Comment by afawcett** [comment] 2016-12-04 22:08
This looks like a platform bug to me. Between the **deploy** operation and the **updateMetadata** operation. By the sounds of it the deploy operation is causing some kind of metadata refresh in the system, but the updateMetadata operation is not. They best way to submit a case like this, is to run your code in the execute anonymous window and capture the XML request being sent. Then send that on your case (removing the need for the salesforce support to understand Apex wrapper). Suggest that they use curl or something like that to submit your XML MD API request to reproduce the issue. I'll close this issue now, but it remains open for further comments, if you want to let me and others known how you got on reporting this.

**Closed by afawcett** 2016-12-04 22:08 UTC
