### ISSUE TITLE
How to add a list button to a object List View?

### ISSUE THREAD

**Issue by SalesforceDev** [financialforcedev/apex-mdapi#55] opened 2014-11-11 07:39 UTC
For example, Enter Setup-->Customize-->Accounts-->Search Layouts, click Account List View. I want to add a List Button to this list view using Apex code. How to do it?

Thanks,
Samba

**Comment by afawcett** [comment] 2015-01-06 21:25
When you review the layout in Salesforce, has the button been added?

**Comment by beckgh** [comment] 2015-01-07 01:38
Yes, the button has been added to the layout, but  the list view does not show the button. In other words, the layout had the button again, but it does not display on the corresponding page. So, why?

Thanks,
Beck

**Comment by afawcett** [comment] 2015-01-09 21:37
Can you include some screen shots of what your seeing for the ListView layout and the List View itself?

**Comment by beckgh** [comment] 2015-01-14 12:13
Thank you for your help.

public static void removeButtonFromSearchLayout(String SObjectName)
  {
    MetadataService.MetadataPort service = createService();
    MetadataService.CustomObject customObject = readCustomObject(SObjectName);

    if(Test.isRunningTest())
    {
      return;
    }

    MetadataService.SearchLayouts sls = customObject.searchLayouts;
    String[] lvButtons = sls.listViewButtons;
    if(lvButtons != null)
    {
      for(Integer i = 0;i < lvButtons.size();i++)
      {
        if(lvButtons[i].equals('DeleteSelectedButton') || lvButtons[i].equals('EditSelectedButton'))
        {
          lvButtons.remove(i);
        }
      }
    }
    
    sls.listViewButtons = lvButtons;

    customObject.searchLayouts = sls;
    List<MetadataService.SaveResult> results = service.updateMetadata(new MetadataService.Metadata[] { customObject });       
  }

  public static void addButtonToSearchLayout(String SObjectName)
  {
    MetadataService.MetadataPort service = createService();
    MetadataService.CustomObject customObject = readCustomObject(SObjectName);

    MetadataService.SearchLayouts sls = customObject.searchLayouts;
    if(sls == null)
    {
      sls = new MetadataService.SearchLayouts();
      sls.listViewButtons = new String[]{};
    }
    if(sls.listViewButtons == null)
    {
      sls.listViewButtons = new String[]{};
    }

    for(Integer i = 0;i < sls.listViewButtons.size();i++)
    {
      if(sls.listViewButtons[i].equals('DeleteSelectedButton') || sls.listViewButtons[i].equals('EditSelectedButton'))
      {
        return;
      }
    }
    
    sls.listViewButtons.add('DeleteSelectedButton');
    sls.listViewButtons.add('EditSelectedButton');
    
    customObject.searchLayouts = sls;
    List<MetadataService.SaveResult> results =  service.updateMetadata(new MetadataService.Metadata[] { customObject });
      
  }

![screen shot 2015-01-14 at 8 06 45 pm](https://cloud.githubusercontent.com/assets/9797997/5738589/0400be3c-9c29-11e4-9b4f-b0c7c46d7e6d.png)

The button is the Delete button in the picture. 

Thanks,
Beck

**Comment by afawcett** [comment] 2015-01-14 20:46
When you view the Account object under Setup, what Buttons are shown?

**Comment by beckgh** [comment] 2015-01-15 02:55
![screen shot 2015-01-15 at 10 50 28 am](https://cloud.githubusercontent.com/assets/9797997/5751817/a00e1da8-9ca4-11e4-93b0-604778d237e9.png)

![screen shot 2015-01-15 at 10 49 35 am](https://cloud.githubusercontent.com/assets/9797997/5751819/a923643e-9ca4-11e4-9c82-efde9a87320b.png)


Thanks,
Beck

**Comment by afawcett** [comment] 2015-01-16 09:38
If the button is My Button shown in the screen shot, it is not showing in the Accounts List View, because you have created it as a 'Detailed Page Button' type. Change the button to a Display Type of List Button and it will be possible to assign it to the List View layout.

![screen shot 2015-01-16 at 09 39 01](https://cloud.githubusercontent.com/assets/1167760/5774209/5437df1c-9d63-11e4-8780-9ff92107bed1.png)

**Comment by afawcett** [comment] 2015-01-24 12:10
I'll close this issue now, let me know if your still struggling and we can re-open.

**Closed by afawcett** 2015-01-24 12:10 UTC
Labels: enhancement

**Comment by beckgh** [comment] 2015-01-26 01:37
Thank you for your help.

**Comment by kalamon** [comment] 2016-08-11 14:11
Hi guys,

I am having the same issue, or very similar. And it manifests itself when I call metadata API from Java, not just from Apex. I have reported it to salesforce forums at https://developer.salesforce.com/forums/ForumsMain?id=906F0000000fyRsIAI

Do you have any idea what could be going on? And the buttons I am trying to add are "massDelete" buttons, so they are kosher for list views

**Comment by afawcett** [comment] 2016-08-14 08:50
Not sure, can you share your Java code snippet?

**Comment by kalamon** [comment] 2016-08-16 09:42
Sure, here you go:


ReadResult result = connection.readMetadata("CustomObject", new String[]{objectName});

Metadata[] records = result.getRecords();

CustomObject customObject = (CustomObject) records[0];

SearchLayouts layouts = customObject.getSearchLayouts();

ArrayList<String> buttons = Lists.newArrayList(layouts.getListViewButtons());

buttons.add(BUTTON_NAME);

layouts.setListViewButtons(buttons.toArray(new String[buttons.size()]));

customObject.setSearchLayouts(layouts);

connection.updateMetadata(new Metadata[]{customObject});

**Comment by afawcett** [comment] 2016-08-18 07:35
This looks broadly ok, how is BUTTON_NAME defined? Also do you have a means to dump the XML your SOAP stack is building to a log? It is often clearer to see issues when looking at the SOAP payload being sent. Also easier IF one needs to communicate with Salesforce Support to send that.

**Comment by bigassforce** [comment] 2018-01-07 23:01
This looks like a Salesforce bug. We reproduced as follows:

1. snapshot org, save search layout **using API**
2. snapshot org, re-save search layout **using GUI**
3. snapshot org, inspect search layouts

**Between snapshots 1. and 2. the expected change is seen:**

[![org metadata snapshot diff 1][1]][1]

**Between snapshots 2. and 3. there are NO ancillary metadata changes visible:**

[![org metadata snapshot diff 2][2]][2]

Safe to say this is surely not working as designed. There are no visible side effects from using the GUI versus the API. The issue always occurs when using the synchronous metadata insert/update/upsert operations.

One workaround is to use the ZIP archive asynchronous deploy for the custom object / search layout. Or indeed to "wiggle the switch" from JavaScript or Apex by deploying a sparse skeleton of the custom object over itself, again with ZIP archive asynchronous operation.

Here is one such "switch wiggler" using Zippex and Apex Metadata API:

    
    Blob pkg = Blob.valueOf(''
        + '<?xml version="1.0" encoding="UTF-8"?>'
        + '<Package xmlns="http://soap.sforce.com/2006/04/metadata">'
        + '    <version>41.0</version>'
        + '    <types>'
        + '        <members>*</members>'
        + '        <name>CustomObject</name>'
        + '    </types>'
        + '</Package>'
    );
    
    Blob customObject = Blob.valueOf(''
        + '<?xml version="1.0" encoding="UTF-8"?>'
        + '<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">'
        + '    <deploymentStatus>Deployed</deploymentStatus>'
        + '    <sharingModel>ReadWrite</sharingModel>'
        + '    <label>Sneeze</label>'
        + '    <pluralLabel>Sneezes</pluralLabel>'
        + '    <nameField>'
        + '        <label>Sneeze Name</label>'
        + '        <type>Text</type>'
        + '    </nameField>'
        + '</CustomObject>'
    );

    Zippex zip = new Zippex();
    zip.addFile('package.xml', pkg, null);
    zip.addFile('objects/Sneeze__c.object', customObject, null);

    MetadataClient.DeployOptions options = new MetadataClient.DeployOptions();
    options.checkOnly = false;
    options.testLevel = 'NoTestRun';

    String zipFile = EncodingUtil.base64Encode(zip.getZipArchive());
    String sessionId = UserInfo.getSessionId();
    MetadataClient client = new MetadataClient(sessionId);
    client.deploy(zipFile, options);

(An empty CustomObject element is insufficient. The label and status fields etc must be provided)

  [1]: https://i.stack.imgur.com/925Q7.png
  [2]: https://i.stack.imgur.com/X69Rw.png

**Comment by afawcett** [comment] 2018-02-04 18:17
@bigassforce thanks for sharing! Inventive as ever! ;-)
