### ISSUE TITLE
Calling MetadataService by passing accessToken to sessionId header?

### ISSUE THREAD

**Issue by ankushsomani09** [financialforcedev/apex-mdapi#118] opened 2016-01-20 06:13 UTC
```
MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = '00D280000019Ho9!AQYAQHQw8W1aRUq9xSk8_kwzWsivlHWOEti0e.atkZ_5a8sFs8r9YMpeBmbtH1OsEPPbvOzWyQIsQWSFSiOp_FAIMLPatyuKm';
        service.timeout_x = 40000;
```

I am trying to give accessToken here instead of sessionId.
It throws invalid session id, But if same accessToekn i use in ANT tool, it works.
what is the alternative way to do this.

**Comment by afawcett** [comment] 2016-01-24 00:05
I'm not sure, this should work in my experience, though i've not tried passing a token obtained outside an Apex context. In theory i see what you mean, this should work if it works from Ant. Might be worth double checking via debug log the token is being sent, it should be looking at your code though. Session Id's are not all always made equal, though calling context should not make a difference here since it's a SOAP call.

**Comment by auctifera-josed** [comment] 2016-02-16 16:37
Hi, I encountered this situation while calling some methods to update metadata from a trigger. Since you can only make callouts from a trigger in an asynchronous context, I implemented the method with the future annotation, and 

> For Apex code that is executed asynchronously, such as @future methods, Batch Apex jobs, or scheduled Apex jobs, getSessionId returns null.

so, I needed to pass the session Id as a parameter in the method, I implemented something like:

```      
@future (callout=true)
public static void addContactPicklistPreference(List<String> preferences, String sessionId){
	Schema.DescribeSObjectResult sObjectDescribe = Contact.sObjectType.getDescribe();
	String picklistFieldName = 'Preference__c';		         

       Picklist_MDT.addPicklistValues(sObjectDescribe, picklistFieldName, artists, sessionId);
}

public static void addPicklistValues(Schema.DescribeSObjectResult sObjectDescribe, String picklistFieldName, List<String> picklistValueNames, String sessionId) {
        MetadataService.MetadataPort service = createService(sessionId);
		...
        handleSaveResults(
            service.updateMetadata(
                new MetadataService.Metadata[] { customField })[0]);
    }

public static MetadataService.MetadataPort createService(String sessionId) {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = sessionId;
        return service;
    }
```

And called the `addContactPicklistPreference` method from trigger context. This worked just fine in salesforce classic but not in lightning, when it triggers in lightning I'm getting `System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID...`.

Maybe @ankushsomani09 encountered this problem in lightning.

**Comment by afawcett** [comment] 2016-02-18 18:13
Interesting i wonder if the Session Id retrieved from UserInfo.getSessionId when running in Lighting Experience context does not have the API access privileges? I'll see if i can get some confirmation on this.

**Comment by auctifera-josed** [comment] 2016-02-22 22:23
Hi @afawcett, you may be interested in reading the [answer to my own question](http://salesforce.stackexchange.com/questions/110515/getting-session-id-in-lightning#111396) where I created a workaround for this limitation.

**Comment by afawcett** [comment] 2016-02-24 18:34
Thanks @auctifera-josed. I have confirmed its a security feature of Apex running in a Lightning context.

**Comment by frup42** [comment] 2016-03-15 21:35
Interesting discussion, looks like it's resolved now. Ok to close @afawcett ?

**Comment by afawcett** [comment] 2016-03-16 21:35
Yes agree i think we can close this one.

**Closed** 2016-03-22 23:43 UTC
Labels: query
